# knowledge.py
tools = [
    # Tools can used for tool_use prompt
    "Tool: OpenApplication. Arguments types: app_path - Use the name of the application specified be the user to get the path from the Relevant apps. Description: Opens, runs or launches an app in the system.",
    "Tool: SetTimer. Arguments types: duration - The duration for the timer. Description: Sets a timer.",
    "Tool: AddTodoList. Arguments types: task - The task to add, location - The location of the task, decide this according to the task. Description: Adds a task to the todo list.",
    "Tool: RemoveTodoList. Arguments types: task - The task to remove. Description: Removes a task from the todo list.",
    "Tool: ListTodoList. Arguments types: none - leave empty or just say none. Description: Lists all tasks in the todo list.",
    "Tool: ClearTodoList. Arguments types: none - leave empty or just say none. Description: Clears all tasks from the todo list.",
    "Tool: AddReminder. Arguments types: reminder - The task to be remembered. Do not include the time, when_to_remind - The time to remind the user. Description: Adds a reminder to a specific time.",
    "Tool: RemoveReminder. Arguments types: reminder - The reminder to remove. Description: Removes a reminder.",
    "Tool: ListReminders. Arguments types: none - leave empty or just say none. Description: Lists all reminders stored in the database.",
    "Tool: MarkReminderAsDone. Arguments types: reminder - The reminder to mark as done. Description: Marks a reminder as done.",
    "Tool: CheckTodoList. Arguments types: task - The task to check. Description: Checks if a task exists in the todo list.",
    "Tool: LockScreen. Arguments types: none - leave empty or just say none. Description: Locks the system.",
    "Tool: ShutdownSystem. Arguments types: none - leave empty or just say none. Description: Shuts down the system.",
    "Tool: RestartSystem. Arguments types: none - leave empty or just say none. Description: Restarts the system.",
    "Tool: SetVolume. Arguments types: volume - The volume level to set. Description: Sets the system volume.",
    "Tool: NoAction. Arguments types: none - leave empty or just say none. Description: Use for general chatting with boss.",
    "Tool: AddLocation. Arguments types: location_name - The name of the location, latitude - The latitude specified in Boss's location, longitude - The longitude specified in Boss's location. Description: Adds a location to the database.",
    "Tool: RemoveLocation. Arguments types: location_name - The name of the location to remove. Description: Removes a location from the database.",
    # "Tool: Remember. Arguments types: none - leave empty or just say none. Description: Remembers important information that is needed like preferences."
]
boss_prefs = [
    # Boss preferences to be used in the relevant info prompt
    "Boss is Chenji Bhargav and he is Indian, mother tongue is Telugu.",
    "Boss's best friend is vemireddy lakshmi praneeth aka praneeth.",
    "Boss's favorite character is Iron Man.",
    "Boss's favorite movie is anything featuring Iron Man.",
    "Boss has a brother named shashank who is blood related to him and a sister named jhanvi.",
    "Boss's favorite food is non-vegetarian.",
    "Boss's favorite drink is coffee.",
    "Boss's favorite dessert is ice cream.",
    "Boss's birthday is on March 15th in 2004.",
    "Boss's favorite color is Red.",
    "Boss's favorite hobby is playing video games.",
    "Boss's favorite sport is cricket.",
]
self_info = [
    # Information about H.A.W.K. to be used in the relevant info prompt
    "H.A.W.K. is an AI assistant designed to help with various tasks.",
    "H.A.W.K. was created by Chenji Bhargav.",
    "H.A.W.K.'s father is J.A.R.V.I.S., another AI assistant.",
    "H.A.W.K. has a context window of 32,768 tokens.",
    "H.A.W.K. can perform tasks such as setting reminders, managing to-do lists, and controlling system functions.",
    "H.A.W.K. is designed to refer to the user respectfully as 'Boss'.",
    "H.A.W.K. can understand and generate human-like text based on prompts.",
    "H.A.W.K. is capable of learning from interactions to improve its responses."
]
info =[
    # General knowledge facts to be used in the relevant info prompt
    "The capital of France is Paris.",
    "The largest planet in our solar system is Jupiter.",
    "The human body has 206 bones.",
    "The Great Wall of China is approximately 13,171 miles long.",
    "The chemical symbol for water is H2O.",
    "The fastest land animal is the cheetah.",
    "The tallest mountain in the world is Mount Everest.",
    "The currency of Japan is the Japanese Yen.",
    "The primary colors are red, blue, and yellow.",
    "The largest ocean on Earth is the Pacific Ocean."
]

app_info = [
    # Relevant apps to be used in the Relevant open_application tool
    "app_name: Access, app_path: C:\\Program Files\\Microsoft Office\\root\\Office16\\MSACCESS.EXE",
    "app_name: Amazon.com, app_path: C:\\Program Files (x86)\\Online Services\\Amazon\\WizLink.exe",
    "app_name: DB Browser (SQLCipher), app_path: C:\\Program Files\\DB Browser for SQLite\\DB Browser for SQLCipher.exe",
    "app_name: DB Browser (SQLite), app_path: C:\\Program Files\\DB Browser for SQLite\\DB Browser for SQLite.exe",
    "app_name: Epic Games Launcher, app_path: C:\\Program Files (x86)\\Epic Games\\Launcher\\Portal\\Binaries\\Win32\\EpicGamesLauncher.exe",
    "app_name: Excel, app_path: C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE",
    "app_name: LastPass, app_path: C:\\Program Files (x86)\\Online Services\\LastPass\\WizLink.exe",
    "app_name: Microsoft Edge, app_path: C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",
    "app_name: MSB, app_path: C:\\Program Files\\Mettl\\MSB\\App\\MSB.exe",
    "app_name: OneNote, app_path: C:\\Program Files\\Microsoft Office\\root\\Office16\\ONENOTE.EXE",
    "app_name: Outlook (classic), app_path: C:\\Program Files\\Microsoft Office\\root\\Office16\\OUTLOOK.EXE",
    "app_name: PowerPoint, app_path: C:\\Program Files\\Microsoft Office\\root\\Office16\\POWERPNT.EXE",
    "app_name: Publisher, app_path: C:\\Program Files\\Microsoft Office\\root\\Office16\\MSPUB.EXE",
    "app_name: Sticky Notes (new), app_path: C:\\Program Files\\Microsoft Office\\root\\Office16\\ONENOTE.EXE",
    "app_name: TechPowerUp GPU-Z, app_path: C:\\Program Files (x86)\\GPU-Z\\GPU-Z.exe",
    "app_name: Word, app_path: C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE",
    "app_name: 7-Zip File Manager, app_path: C:\\Program Files\\7-Zip\\7zFM.exe",
    "app_name: Remote Desktop Connection, app_path: C:\\WINDOWS\\system32\\mstsc.exe",
    "app_name: Steps Recorder, app_path: C:\\WINDOWS\\system32\\psr.exe",
    "app_name: Windows Media Player Legacy, app_path: C:\\Program Files (x86)\\Windows Media Player\\wmplayer.exe",
    "app_name: XPS Viewer, app_path: C:\\WINDOWS\\system32\\xpsrchvw.exe",
    "app_name: Character Map, app_path: C:\\WINDOWS\\system32\\charmap.exe",
    "app_name: dfrgui, app_path: C:\\WINDOWS\\system32\\dfrgui.exe",
    "app_name: Disk Cleanup, app_path: C:\\WINDOWS\\system32\\cleanmgr.exe",
    "app_name: iSCSI Initiator, app_path: C:\\WINDOWS\\system32\\iscsicpl.exe",
    "app_name: Memory Diagnostics Tool, app_path: C:\\WINDOWS\\system32\\MdSched.exe",
    "app_name: ODBC Data Sources (32-bit), app_path: C:\\WINDOWS\\syswow64\\odbcad32.exe",
    "app_name: ODBC Data Sources (64-bit), app_path: C:\\WINDOWS\\system32\\odbcad32.exe",
    "app_name: RecoveryDrive, app_path: C:\\WINDOWS\\system32\\RecoveryDrive.exe",
    "app_name: Registry Editor, app_path: C:\\WINDOWS\\regedit.exe",
    "app_name: Resource Monitor, app_path: C:\\WINDOWS\\system32\\perfmon.exe",
    "app_name: System Configuration, app_path: C:\\WINDOWS\\system32\\msconfig.exe",
    "app_name: System Information, app_path: C:\\WINDOWS\\system32\\msinfo32.exe",
    "app_name: AMD Bug Report Tool, app_path: C:\\Windows\\SysWOW64\\AMDBugReportTool.exe",
    "app_name: Android Studio, app_path: C:\\Program Files\\Android\\Android Studio3\\bin\\studio64.exe",
    "app_name: Bitdefender, app_path: C:\\Program Files\\Bitdefender\\Bitdefender Security App\\seccenter.exe",
    "app_name: Bitdefender VPN, app_path: C:\\Program Files\\Bitdefender\\Bitdefender VPN\\bdvpnuiapp.exe",
    "app_name: CMake (cmake-gui), app_path: C:\\Program Files\\CMake\\bin\\cmake-gui.exe",
    "app_name: CPU-Z, app_path: C:\\Program Files\\CPUID\\CPU-Z\\cpuz.exe",
    "app_name: Git Bash, app_path: C:\\Program Files\\Git\\git-bash.exe",
    "app_name: Git CMD, app_path: C:\\Program Files\\Git\\git-cmd.exe",
    "app_name: Git GUI, app_path: C:\\Program Files\\Git\\cmd\\git-gui.exe",
    "app_name: HWiNFO® 64, app_path: C:\\Program Files\\HWiNFO64\\HWiNFO64.EXE",
    "app_name: PyCharm Community Edition 2024.2.1, app_path: C:\\Program Files\\JetBrains\\PyCharm Community Edition 2024.2.1\\bin\\pycharm64.exe",
    "app_name: Office Language Preferences, app_path: C:\\Program Files\\Microsoft Office\\root\\Office16\\SETLANG.EXE",
    "app_name: MySQL Shell, app_path: C:\\Program Files\\MySQL\\MySQL Shell 9.3\\bin\\mysqlsh.exe",
    "app_name: Node.js command prompt, app_path: C:\\Windows\\System32\\cmd.exe",
    "app_name: Node.js, app_path: C:\\Program Files\\nodejs\\node.exe",
    "app_name: Oracle VirtualBox, app_path: C:\\Program Files\\Oracle\\VirtualBox\\VirtualBox.exe",
    "app_name: Proton VPN, app_path: C:\\Program Files\\Proton\\VPN\\ProtonVPN.Launcher.exe",
    "app_name: IDLE (Python 3.13 64-bit), app_path: C:\\Python313\\pythonw.exe",
    "app_name: Python 3.13 (64-bit), app_path: C:\\Python313\\python.exe",
    "app_name: Python 3.13 Module Docs (64-bit), app_path: C:\\Python313\\python.exe",
    "app_name: Steam, app_path: C:\\Program Files (x86)\\Steam\\steam.exe",
    "app_name: Task Manager, app_path: C:\\WINDOWS\\system32\\taskmgr.exe",
    "app_name: VLC media player - reset preferences and cache files, app_path: C:\\Program Files\\VideoLAN\\VLC\\vlc.exe",
    "app_name: VLC media player skinned, app_path: C:\\Program Files\\VideoLAN\\VLC\\vlc.exe",
    "app_name: VLC media player, app_path: C:\\Program Files\\VideoLAN\\VLC\\vlc.exe",
    "app_name: Developer Command Prompt for VS 2019, app_path: C:\\Windows\\System32\\cmd.exe",
    "app_name: Developer PowerShell for VS 2019, app_path: C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe",
    "app_name: x64 Native Tools Command Prompt for VS 2019, app_path: C:\\Windows\\System32\\cmd.exe",
    "app_name: x64_x86 Cross Tools Command Prompt for VS 2019, app_path: C:\\Windows\\System32\\cmd.exe",
    "app_name: x86 Native Tools Command Prompt for VS 2019, app_path: C:\\Windows\\System32\\cmd.exe",
    "app_name: x86_x64 Cross Tools Command Prompt for VS 2019, app_path: C:\\Windows\\System32\\cmd.exe",
    "app_name: Debuggable Package Manager, app_path: C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe",
    "app_name: Developer Command Prompt for VS 2022, app_path: C:\\Windows\\System32\\cmd.exe",
    "app_name: Developer PowerShell for VS 2022, app_path: C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe",
    "app_name: x64 Native Tools Command Prompt for VS 2022, app_path: C:\\Windows\\System32\\cmd.exe",
    "app_name: x64_x86 Cross Tools Command Prompt for VS 2022, app_path: C:\\Windows\\System32\\cmd.exe",
    "app_name: x86 Native Tools Command Prompt for VS 2022, app_path: C:\\Windows\\System32\\cmd.exe",
    "app_name: x86_x64 Cross Tools Command Prompt for VS 2022, app_path: C:\\Windows\\System32\\cmd.exe",
    "app_name: Maintenance Tool, app_path: C:\\VulkanSDK\\1.4.328.1\\maintenancetool.exe",
    "app_name: Vulkan Caps Viewer, app_path: C:\\VulkanSDK\\1.4.328.1\\Bin\\vulkanCapsViewer.exe",
    "app_name: Vulkan Configurator, app_path: C:\\VulkanSDK\\1.4.328.1\\Bin\\vkconfig-gui.exe",
    "app_name: Vulkan Cube, app_path: C:\\VulkanSDK\\1.4.328.1\\Bin\\vkcube.exe",
    "app_name: Application Verifier (X64), app_path: C:\\Windows\\System32\\appverif.exe",
    "app_name: Application Verifier (WOW), app_path: C:\\Windows\\SysWOW64\\appverif.exe",
    "app_name: Windows App Cert Kit, app_path: C:\\Program Files (x86)\\Windows Kits\\10\\App Certification Kit\\appcertui.exe",
    "app_name: Windows Software Development Kit, app_path: C:\\WINDOWS\\explorer.exe",
    "app_name: Windows PowerShell ISE (x86), app_path: C:\\WINDOWS\\syswow64\\WindowsPowerShell\\v1.0\\PowerShell_ISE.exe",
    "app_name: Windows PowerShell ISE, app_path: C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\PowerShell_ISE.exe",
    "app_name: Administrative Tools, app_path: C:\\WINDOWS\\system32\\control.exe",
    "app_name: Arduino IDE, app_path: C:\\Users\\chenj\\AppData\\Local\\Programs\\Arduino IDE\\Arduino IDE.exe",
    "app_name: Figma, app_path: C:\\Users\\chenj\\AppData\\Local\\Figma\\app-125.5.6\\Figma.exe",
    "app_name: LM Studio, app_path: C:\\Users\\chenj\\AppData\\Local\\Programs\\LM Studio\\LM Studio.exe",
    "app_name: Ollama, app_path: C:\\Users\\chenj\\AppData\\Local\\Programs\\Ollama\\ollama app.exe",
    "app_name: OneDrive, app_path: C:\\Users\\chenj\\AppData\\Local\\Microsoft\\OneDrive\\OneDrive.exe",
    "app_name: Opera Browser, app_path: C:\\Users\\chenj\\AppData\\Local\\Programs\\Opera\\opera.exe",
    "app_name: uTorrent Web, app_path: C:\\Users\\chenj\\AppData\\Roaming\\uTorrent Web\\utweb.exe",
    "app_name: WPS Office, app_path: C:\\Users\\chenj\\AppData\\Local\\Kingsoft\\WPS Office\\ksolaunch.exe",
    "app_name: WPS PDF, app_path: C:\\Users\\chenj\\AppData\\Local\\Kingsoft\\WPS Office\\ksolaunch.exe",
    "app_name: WPS Sheets, app_path: C:\\Users\\chenj\\AppData\\Local\\Kingsoft\\WPS Office\\ksolaunch.exe",
    "app_name: WPS Slides, app_path: C:\\Users\\chenj\\AppData\\Local\\Kingsoft\\WPS Office\\ksolaunch.exe",
    "app_name: WPS Docs, app_path: C:\\Users\\chenj\\AppData\\Local\\Kingsoft\\WPS Office\\ksolaunch.exe",
    "app_name: LiveCaptions, app_path: C:\\WINDOWS\\system32\\LiveCaptions.exe",
    "app_name: Magnify, app_path: C:\\WINDOWS\\system32\\magnify.exe",
    "app_name: Narrator, app_path: C:\\WINDOWS\\system32\\narrator.exe",
    "app_name: On-Screen Keyboard, app_path: C:\\WINDOWS\\system32\\osk.exe",
    "app_name: VoiceAccess, app_path: C:\\WINDOWS\\system32\\voiceaccess.exe",
    "app_name: Anaconda Navigator, app_path: C:\\Users\\chenj\\anaconda3\\pythonw.exe",
    "app_name: Anaconda PowerShell Prompt, app_path: C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "app_name: Anaconda Prompt, app_path: C:\\Windows\\System32\\cmd.exe",
    "app_name: Jupyter Notebook, app_path: C:\\Users\\chenj\\anaconda3\\python.exe",
    "app_name: Spyder, app_path: C:\\Users\\chenj\\anaconda3\\pythonw.exe",
    "app_name: EonVPN Beta, app_path: C:\\Program Files (x86)\\EonVPN Beta\\EonVPN Beta.exe",
    "app_name: GitHub Desktop, app_path: C:\\Users\\chenj\\AppData\\Local\\GitHubDesktop\\GitHubDesktop.exe",
    "app_name: Insomnia, app_path: C:\\Users\\chenj\\AppData\\Local\\insomnia\\Insomnia.exe",
    "app_name: Rockstar Games Launcher, app_path: C:\\Program Files\\Rockstar Games\\Launcher\\LauncherPatcher.exe",
    "app_name: Command Prompt, app_path: C:\\WINDOWS\\system32\\cmd.exe",
    "app_name: Ubisoft Connect, app_path: C:\\Program Files (x86)\\Ubisoft\\Ubisoft Game Launcher\\UbisoftConnect.exe",
    "app_name: Visual Studio Code, app_path: C:\\Users\\chenj\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
    "app_name: Windows PowerShell (x86), app_path: C:\\Windows\\SysWOW64\\WindowsPowerShell\\v1.0\\powershell.exe",
    "app_name: Windows PowerShell, app_path: C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "app_name: WPS Office Configuration Tools, app_path: C:\\Users\\chenj\\AppData\\Local\\Kingsoft\\WPS Office\\12.2.0.23131\\office6\\ksomisc.exe",
    "app_name: Zoom Workplace, app_path: C:\\Users\\chenj\\AppData\\Roaming\\Zoom\\bin\\Zoom.exe",
    "app_name: BHARGAV (cmrit.ac.in) - Chrome, app_path: C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
    "app_name: Bluetooth File Transfer, app_path: C:\\Windows\\System32\\fsquirt.exe",
    "app_name: Ubuntu, app_path: C:\\Program Files\\WSL\\wsl.exe",
]

locations = [
    # Locations stored in the database for location-based reminders
    
]
